required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "master"

[[override]]
  name = "k8s.io/gengo"
  branch = "master"

# vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:104:16:
# unknown field 'CaseSensitive' in struct literal of type jsoniter.Config
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "k8s.io/code-generator"
  revision = "ae218e2412520541341ca1a01aaeb90b592245e3"
